// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

module com.azure.client.one {
    requires transitive com.azure.core;
    exports com.azure.client.one;
    exports com.azure.client.one.models;
    opens com.azure.client.one.models to com.azure.core;
}