// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

module com.azure.client.customization {
    requires transitive com.azure.core;

    exports com.azure.client.customization;
    exports com.azure.client.customization.models;

    opens com.azure.client.customization.implementation.models to com.azure.core;
    opens com.azure.client.customization.models to com.azure.core;
}
