// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

module com.azure.auth.oauth {
    requires transitive com.azure.core;
    exports com.azure.auth.oauth;
    exports com.azure.auth.oauth.models;
    opens com.azure.auth.oauth.models to com.azure.core;
}