// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.auth.apikey.implementation;

import com.azure.auth.apikey.ApiKeyAuthenticationServiceVersion;
import com.azure.core.http.HttpPipeline;
import com.azure.core.http.HttpPipelineBuilder;
import com.azure.core.http.policy.RetryPolicy;
import com.azure.core.http.policy.UserAgentPolicy;
import com.azure.core.util.serializer.JacksonAdapter;
import com.azure.core.util.serializer.SerializerAdapter;

/**
 * Initializes a new instance of the ApiKeyAuthenticationClient type.
 */
public final class ApiKeyAuthenticationClientImpl {
    /**
     * Supported auth endpoints (protocol and hostname, for example:
     * https://westus.api.auth.com).
     */
    private final String endpoint;

    /**
     * Gets Supported auth endpoints (protocol and hostname, for example:
     * https://westus.api.auth.com).
     * 
     * @return the endpoint value.
     */
    public String getEndpoint() {
        return this.endpoint;
    }

    /**
     * Service version.
     */
    private final ApiKeyAuthenticationServiceVersion serviceVersion;

    /**
     * Gets Service version.
     * 
     * @return the serviceVersion value.
     */
    public ApiKeyAuthenticationServiceVersion getServiceVersion() {
        return this.serviceVersion;
    }

    /**
     * The HTTP pipeline to send requests through.
     */
    private final HttpPipeline httpPipeline;

    /**
     * Gets The HTTP pipeline to send requests through.
     * 
     * @return the httpPipeline value.
     */
    public HttpPipeline getHttpPipeline() {
        return this.httpPipeline;
    }

    /**
     * The serializer to serialize an object into a string.
     */
    private final SerializerAdapter serializerAdapter;

    /**
     * Gets The serializer to serialize an object into a string.
     * 
     * @return the serializerAdapter value.
     */
    public SerializerAdapter getSerializerAdapter() {
        return this.serializerAdapter;
    }

    /**
     * The ApiKeyAuthSamplesImpl object to access its operations.
     */
    private final ApiKeyAuthSamplesImpl apiKeyAuthSamples;

    /**
     * Gets the ApiKeyAuthSamplesImpl object to access its operations.
     * 
     * @return the ApiKeyAuthSamplesImpl object.
     */
    public ApiKeyAuthSamplesImpl getApiKeyAuthSamples() {
        return this.apiKeyAuthSamples;
    }

    /**
     * Initializes an instance of ApiKeyAuthenticationClient client.
     * 
     * @param endpoint Supported auth endpoints (protocol and hostname, for example:
     * https://westus.api.auth.com).
     * @param serviceVersion Service version.
     */
    public ApiKeyAuthenticationClientImpl(String endpoint, ApiKeyAuthenticationServiceVersion serviceVersion) {
        this(new HttpPipelineBuilder().policies(new UserAgentPolicy(), new RetryPolicy()).build(),
            JacksonAdapter.createDefaultSerializerAdapter(), endpoint, serviceVersion);
    }

    /**
     * Initializes an instance of ApiKeyAuthenticationClient client.
     * 
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param endpoint Supported auth endpoints (protocol and hostname, for example:
     * https://westus.api.auth.com).
     * @param serviceVersion Service version.
     */
    public ApiKeyAuthenticationClientImpl(HttpPipeline httpPipeline, String endpoint,
        ApiKeyAuthenticationServiceVersion serviceVersion) {
        this(httpPipeline, JacksonAdapter.createDefaultSerializerAdapter(), endpoint, serviceVersion);
    }

    /**
     * Initializes an instance of ApiKeyAuthenticationClient client.
     * 
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param serializerAdapter The serializer to serialize an object into a string.
     * @param endpoint Supported auth endpoints (protocol and hostname, for example:
     * https://westus.api.auth.com).
     * @param serviceVersion Service version.
     */
    public ApiKeyAuthenticationClientImpl(HttpPipeline httpPipeline, SerializerAdapter serializerAdapter,
        String endpoint, ApiKeyAuthenticationServiceVersion serviceVersion) {
        this.httpPipeline = httpPipeline;
        this.serializerAdapter = serializerAdapter;
        this.endpoint = endpoint;
        this.serviceVersion = serviceVersion;
        this.apiKeyAuthSamples = new ApiKeyAuthSamplesImpl(this);
    }
}
