// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.auth.oauth.implementation;

import com.azure.auth.oauth.OAuthAuthenticationServiceVersion;
import com.azure.core.http.HttpPipeline;
import com.azure.core.http.HttpPipelineBuilder;
import com.azure.core.http.policy.RetryPolicy;
import com.azure.core.http.policy.UserAgentPolicy;
import com.azure.core.util.serializer.JacksonAdapter;
import com.azure.core.util.serializer.SerializerAdapter;

/**
 * Initializes a new instance of the OAuthAuthenticationClient type.
 */
public final class OAuthAuthenticationClientImpl {
    /**
     * Supported auth endpoints (protocol and hostname, for example:
     * https://westus.oauth.auth.com).
     */
    private final String endpoint;

    /**
     * Gets Supported auth endpoints (protocol and hostname, for example:
     * https://westus.oauth.auth.com).
     * 
     * @return the endpoint value.
     */
    public String getEndpoint() {
        return this.endpoint;
    }

    /**
     * Service version.
     */
    private final OAuthAuthenticationServiceVersion serviceVersion;

    /**
     * Gets Service version.
     * 
     * @return the serviceVersion value.
     */
    public OAuthAuthenticationServiceVersion getServiceVersion() {
        return this.serviceVersion;
    }

    /**
     * The HTTP pipeline to send requests through.
     */
    private final HttpPipeline httpPipeline;

    /**
     * Gets The HTTP pipeline to send requests through.
     * 
     * @return the httpPipeline value.
     */
    public HttpPipeline getHttpPipeline() {
        return this.httpPipeline;
    }

    /**
     * The serializer to serialize an object into a string.
     */
    private final SerializerAdapter serializerAdapter;

    /**
     * Gets The serializer to serialize an object into a string.
     * 
     * @return the serializerAdapter value.
     */
    public SerializerAdapter getSerializerAdapter() {
        return this.serializerAdapter;
    }

    /**
     * The OAuthSamplesImpl object to access its operations.
     */
    private final OAuthSamplesImpl oAuthSamples;

    /**
     * Gets the OAuthSamplesImpl object to access its operations.
     * 
     * @return the OAuthSamplesImpl object.
     */
    public OAuthSamplesImpl getOAuthSamples() {
        return this.oAuthSamples;
    }

    /**
     * Initializes an instance of OAuthAuthenticationClient client.
     * 
     * @param endpoint Supported auth endpoints (protocol and hostname, for example:
     * https://westus.oauth.auth.com).
     * @param serviceVersion Service version.
     */
    public OAuthAuthenticationClientImpl(String endpoint, OAuthAuthenticationServiceVersion serviceVersion) {
        this(new HttpPipelineBuilder().policies(new UserAgentPolicy(), new RetryPolicy()).build(),
            JacksonAdapter.createDefaultSerializerAdapter(), endpoint, serviceVersion);
    }

    /**
     * Initializes an instance of OAuthAuthenticationClient client.
     * 
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param endpoint Supported auth endpoints (protocol and hostname, for example:
     * https://westus.oauth.auth.com).
     * @param serviceVersion Service version.
     */
    public OAuthAuthenticationClientImpl(HttpPipeline httpPipeline, String endpoint,
        OAuthAuthenticationServiceVersion serviceVersion) {
        this(httpPipeline, JacksonAdapter.createDefaultSerializerAdapter(), endpoint, serviceVersion);
    }

    /**
     * Initializes an instance of OAuthAuthenticationClient client.
     * 
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param serializerAdapter The serializer to serialize an object into a string.
     * @param endpoint Supported auth endpoints (protocol and hostname, for example:
     * https://westus.oauth.auth.com).
     * @param serviceVersion Service version.
     */
    public OAuthAuthenticationClientImpl(HttpPipeline httpPipeline, SerializerAdapter serializerAdapter,
        String endpoint, OAuthAuthenticationServiceVersion serviceVersion) {
        this.httpPipeline = httpPipeline;
        this.serializerAdapter = serializerAdapter;
        this.endpoint = endpoint;
        this.serviceVersion = serviceVersion;
        this.oAuthSamples = new OAuthSamplesImpl(this);
    }
}
