// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.auth.oauth;

import com.azure.auth.oauth.implementation.OAuthSamplesImpl;
import com.azure.auth.oauth.models.ResourceOperationStatusFooFooError;
import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.http.rest.Response;
import com.azure.core.util.BinaryData;
import com.azure.core.util.FluxUtil;
import reactor.core.publisher.Mono;

/**
 * Initializes a new instance of the asynchronous OAuthAuthenticationClient type.
 */
@ServiceClient(builder = OAuthAuthenticationClientBuilder.class, isAsync = true)
public final class OAuthAuthenticationAsyncClient {
    @Generated
    private final OAuthSamplesImpl serviceClient;

    /**
     * Initializes an instance of OAuthAuthenticationAsyncClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Generated
    OAuthAuthenticationAsyncClient(OAuthSamplesImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * Gets status of a Widget operation.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>{@code
     * {
     *     id: String (Required)
     *     status: String(NotStarted/Running/Succeeded/Failed/Canceled) (Required)
     *     error (Optional): {
     *         code: String (Required)
     *         message: String (Required)
     *         target: String (Optional)
     *         details (Optional): [
     *             (recursive schema, see above)
     *         ]
     *         innererror (Optional): {
     *             code: String (Optional)
     *             innererror (Optional): (recursive schema, see innererror above)
     *         }
     *     }
     *     result (Optional): {
     *         fooId: String (Required)
     *     }
     * }
     * }</pre>
     * 
     * @param fooId A sequence of textual characters.
     * @param operationId The unique ID of the operation.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return status of a Widget operation along with {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<BinaryData>> getFooWithResponse(String fooId, String operationId,
        RequestOptions requestOptions) {
        return this.serviceClient.getFooWithResponseAsync(fooId, operationId, requestOptions);
    }

    /**
     * Gets status of a Widget operation.
     * 
     * @param fooId A sequence of textual characters.
     * @param operationId The unique ID of the operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return status of a Widget operation on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<ResourceOperationStatusFooFooError> getFoo(String fooId, String operationId) {
        // Generated convenience method for getFooWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return getFooWithResponse(fooId, operationId, requestOptions).flatMap(FluxUtil::toMono)
            .map(protocolMethodData -> protocolMethodData.toObject(ResourceOperationStatusFooFooError.class));
    }
}
