// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.auth.all.implementation;

import com.azure.auth.all.AllAuthenticationServiceVersion;
import com.azure.core.http.HttpPipeline;
import com.azure.core.http.HttpPipelineBuilder;
import com.azure.core.http.policy.RetryPolicy;
import com.azure.core.http.policy.UserAgentPolicy;
import com.azure.core.util.serializer.JacksonAdapter;
import com.azure.core.util.serializer.SerializerAdapter;

/**
 * Initializes a new instance of the AllAuthenticationClient type.
 */
public final class AllAuthenticationClientImpl {
    /**
     * Supported auth endpoints (protocol and hostname, for example:
     * https://westus.all.auth.com).
     */
    private final String endpoint;

    /**
     * Gets Supported auth endpoints (protocol and hostname, for example:
     * https://westus.all.auth.com).
     * 
     * @return the endpoint value.
     */
    public String getEndpoint() {
        return this.endpoint;
    }

    /**
     * Service version.
     */
    private final AllAuthenticationServiceVersion serviceVersion;

    /**
     * Gets Service version.
     * 
     * @return the serviceVersion value.
     */
    public AllAuthenticationServiceVersion getServiceVersion() {
        return this.serviceVersion;
    }

    /**
     * The HTTP pipeline to send requests through.
     */
    private final HttpPipeline httpPipeline;

    /**
     * Gets The HTTP pipeline to send requests through.
     * 
     * @return the httpPipeline value.
     */
    public HttpPipeline getHttpPipeline() {
        return this.httpPipeline;
    }

    /**
     * The serializer to serialize an object into a string.
     */
    private final SerializerAdapter serializerAdapter;

    /**
     * Gets The serializer to serialize an object into a string.
     * 
     * @return the serializerAdapter value.
     */
    public SerializerAdapter getSerializerAdapter() {
        return this.serializerAdapter;
    }

    /**
     * The AllAuthSamplesImpl object to access its operations.
     */
    private final AllAuthSamplesImpl allAuthSamples;

    /**
     * Gets the AllAuthSamplesImpl object to access its operations.
     * 
     * @return the AllAuthSamplesImpl object.
     */
    public AllAuthSamplesImpl getAllAuthSamples() {
        return this.allAuthSamples;
    }

    /**
     * Initializes an instance of AllAuthenticationClient client.
     * 
     * @param endpoint Supported auth endpoints (protocol and hostname, for example:
     * https://westus.all.auth.com).
     * @param serviceVersion Service version.
     */
    public AllAuthenticationClientImpl(String endpoint, AllAuthenticationServiceVersion serviceVersion) {
        this(new HttpPipelineBuilder().policies(new UserAgentPolicy(), new RetryPolicy()).build(),
            JacksonAdapter.createDefaultSerializerAdapter(), endpoint, serviceVersion);
    }

    /**
     * Initializes an instance of AllAuthenticationClient client.
     * 
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param endpoint Supported auth endpoints (protocol and hostname, for example:
     * https://westus.all.auth.com).
     * @param serviceVersion Service version.
     */
    public AllAuthenticationClientImpl(HttpPipeline httpPipeline, String endpoint,
        AllAuthenticationServiceVersion serviceVersion) {
        this(httpPipeline, JacksonAdapter.createDefaultSerializerAdapter(), endpoint, serviceVersion);
    }

    /**
     * Initializes an instance of AllAuthenticationClient client.
     * 
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param serializerAdapter The serializer to serialize an object into a string.
     * @param endpoint Supported auth endpoints (protocol and hostname, for example:
     * https://westus.all.auth.com).
     * @param serviceVersion Service version.
     */
    public AllAuthenticationClientImpl(HttpPipeline httpPipeline, SerializerAdapter serializerAdapter, String endpoint,
        AllAuthenticationServiceVersion serviceVersion) {
        this.httpPipeline = httpPipeline;
        this.serializerAdapter = serializerAdapter;
        this.endpoint = endpoint;
        this.serviceVersion = serviceVersion;
        this.allAuthSamples = new AllAuthSamplesImpl(this);
    }
}
