// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.operations.crud.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import com.azure.operations.crud.implementation.JsonMergePatchHelper;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;

/**
 * A widget.
 */
@Fluent
public final class Widget implements JsonSerializable<Widget> {
    /*
     * The widget name.
     */
    @Generated
    private String name;

    /*
     * The ID of the widget's manufacturer.
     */
    @Generated
    private String manufacturerId;

    @Generated
    private boolean jsonMergePatch;

    /**
     * Stores updated model property, the value is property name, not serialized name.
     */
    @Generated
    private final Set<String> updatedProperties = new HashSet<>();

    @Generated
    void serializeAsJsonMergePatch(boolean jsonMergePatch) {
        this.jsonMergePatch = jsonMergePatch;
    }

    static {
        JsonMergePatchHelper.setWidgetAccessor((model, jsonMergePatchEnabled) -> {
            model.serializeAsJsonMergePatch(jsonMergePatchEnabled);
            return model;
        });
    }

    /**
     * Creates an instance of Widget class.
     */
    @Generated
    public Widget() {
    }

    /**
     * Get the name property: The widget name.
     * 
     * @return the name value.
     */
    @Generated
    public String getName() {
        return this.name;
    }

    /**
     * Get the manufacturerId property: The ID of the widget's manufacturer.
     * 
     * @return the manufacturerId value.
     */
    @Generated
    public String getManufacturerId() {
        return this.manufacturerId;
    }

    /**
     * Set the manufacturerId property: The ID of the widget's manufacturer.
     * <p>Required when create the resource.</p>
     * 
     * @param manufacturerId the manufacturerId value to set.
     * @return the Widget object itself.
     */
    @Generated
    public Widget setManufacturerId(String manufacturerId) {
        this.manufacturerId = manufacturerId;
        this.updatedProperties.add("manufacturerId");
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        if (jsonMergePatch) {
            return toJsonMergePatch(jsonWriter);
        } else {
            jsonWriter.writeStartObject();
            jsonWriter.writeStringField("manufacturerId", this.manufacturerId);
            return jsonWriter.writeEndObject();
        }
    }

    @Generated
    private JsonWriter toJsonMergePatch(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        if (updatedProperties.contains("manufacturerId")) {
            if (this.manufacturerId == null) {
                jsonWriter.writeNullField("manufacturerId");
            } else {
                jsonWriter.writeStringField("manufacturerId", this.manufacturerId);
            }
        }
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of Widget from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of Widget if the JsonReader was pointing to an instance of it, or null if it was pointing to
     * JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the Widget.
     */
    @Generated
    public static Widget fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String name = null;
            String manufacturerId = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("name".equals(fieldName)) {
                    name = reader.getString();
                } else if ("manufacturerId".equals(fieldName)) {
                    manufacturerId = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            Widget deserializedWidget = new Widget();
            deserializedWidget.name = name;
            deserializedWidget.manufacturerId = manufacturerId;

            return deserializedWidget;
        });
    }
}
