// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.client.one.implementation;

import com.azure.client.one.ClientOneServiceVersion;
import com.azure.core.http.HttpPipeline;
import com.azure.core.http.HttpPipelineBuilder;
import com.azure.core.http.policy.RetryPolicy;
import com.azure.core.http.policy.UserAgentPolicy;
import com.azure.core.util.serializer.JacksonAdapter;
import com.azure.core.util.serializer.SerializerAdapter;

/**
 * Initializes a new instance of the ClientOneClient type.
 */
public final class ClientOneClientImpl {
    /**
     * Supported endpoints (protocol and hostname, for example:
     * https://westus.client.auth.com).
     */
    private final String endpoint;

    /**
     * Gets Supported endpoints (protocol and hostname, for example:
     * https://westus.client.auth.com).
     * 
     * @return the endpoint value.
     */
    public String getEndpoint() {
        return this.endpoint;
    }

    /**
     * Service version.
     */
    private final ClientOneServiceVersion serviceVersion;

    /**
     * Gets Service version.
     * 
     * @return the serviceVersion value.
     */
    public ClientOneServiceVersion getServiceVersion() {
        return this.serviceVersion;
    }

    /**
     * The HTTP pipeline to send requests through.
     */
    private final HttpPipeline httpPipeline;

    /**
     * Gets The HTTP pipeline to send requests through.
     * 
     * @return the httpPipeline value.
     */
    public HttpPipeline getHttpPipeline() {
        return this.httpPipeline;
    }

    /**
     * The serializer to serialize an object into a string.
     */
    private final SerializerAdapter serializerAdapter;

    /**
     * Gets The serializer to serialize an object into a string.
     * 
     * @return the serializerAdapter value.
     */
    public SerializerAdapter getSerializerAdapter() {
        return this.serializerAdapter;
    }

    /**
     * The ClientOneSamplesImpl object to access its operations.
     */
    private final ClientOneSamplesImpl clientOneSamples;

    /**
     * Gets the ClientOneSamplesImpl object to access its operations.
     * 
     * @return the ClientOneSamplesImpl object.
     */
    public ClientOneSamplesImpl getClientOneSamples() {
        return this.clientOneSamples;
    }

    /**
     * Initializes an instance of ClientOneClient client.
     * 
     * @param endpoint Supported endpoints (protocol and hostname, for example:
     * https://westus.client.auth.com).
     * @param serviceVersion Service version.
     */
    public ClientOneClientImpl(String endpoint, ClientOneServiceVersion serviceVersion) {
        this(new HttpPipelineBuilder().policies(new UserAgentPolicy(), new RetryPolicy()).build(),
            JacksonAdapter.createDefaultSerializerAdapter(), endpoint, serviceVersion);
    }

    /**
     * Initializes an instance of ClientOneClient client.
     * 
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param endpoint Supported endpoints (protocol and hostname, for example:
     * https://westus.client.auth.com).
     * @param serviceVersion Service version.
     */
    public ClientOneClientImpl(HttpPipeline httpPipeline, String endpoint, ClientOneServiceVersion serviceVersion) {
        this(httpPipeline, JacksonAdapter.createDefaultSerializerAdapter(), endpoint, serviceVersion);
    }

    /**
     * Initializes an instance of ClientOneClient client.
     * 
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param serializerAdapter The serializer to serialize an object into a string.
     * @param endpoint Supported endpoints (protocol and hostname, for example:
     * https://westus.client.auth.com).
     * @param serviceVersion Service version.
     */
    public ClientOneClientImpl(HttpPipeline httpPipeline, SerializerAdapter serializerAdapter, String endpoint,
        ClientOneServiceVersion serviceVersion) {
        this.httpPipeline = httpPipeline;
        this.serializerAdapter = serializerAdapter;
        this.endpoint = endpoint;
        this.serviceVersion = serviceVersion;
        this.clientOneSamples = new ClientOneSamplesImpl(this);
    }
}
