// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

module com.azure.auth.apikey {
    requires transitive com.azure.core;
    exports com.azure.auth.apikey;
    exports com.azure.auth.apikey.models;
    opens com.azure.auth.apikey.models to com.azure.core;
}