// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

module com.azure.client.multi {
    requires transitive com.azure.core;
    exports com.azure.client.multi;
    exports com.azure.client.multi.models;
    opens com.azure.client.multi.models to com.azure.core;
}