// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

module com.azure.auth.all {
    requires transitive com.azure.core;

    exports com.azure.auth.all;
    exports com.azure.auth.all.models;

    opens com.azure.auth.all.models to com.azure.core;
}
