// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.auth.apikey;

import com.azure.core.util.ServiceVersion;

/**
 * Service version of ApiKeyAuthenticationClient.
 */
public enum ApiKeyAuthenticationServiceVersion implements ServiceVersion {
    /**
     * Enum value 2022-08-30.
     */
    V2022_08_30("2022-08-30");

    private final String version;

    ApiKeyAuthenticationServiceVersion(String version) {
        this.version = version;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getVersion() {
        return this.version;
    }

    /**
     * Gets the latest service version supported by this client library.
     * 
     * @return The latest {@link ApiKeyAuthenticationServiceVersion}.
     */
    public static ApiKeyAuthenticationServiceVersion getLatest() {
        return V2022_08_30;
    }
}
