// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.auth.all.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The Foo model.
 */
@Immutable
public final class Foo implements JsonSerializable<Foo> {
    /*
     * The fooId property.
     */
    @Generated
    private String fooId;

    /**
     * Creates an instance of Foo class.
     */
    @Generated
    private Foo() {
    }

    /**
     * Get the fooId property: The fooId property.
     * 
     * @return the fooId value.
     */
    @Generated
    public String getFooId() {
        return this.fooId;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of Foo from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of Foo if the JsonReader was pointing to an instance of it, or null if it was pointing to
     * JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the Foo.
     */
    @Generated
    public static Foo fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String fooId = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("fooId".equals(fieldName)) {
                    fooId = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            Foo deserializedFoo = new Foo();
            deserializedFoo.fooId = fooId;

            return deserializedFoo;
        });
    }
}
