// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.client.multi.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The Bar model.
 */
@Immutable
public final class Bar implements JsonSerializable<Bar> {
    /*
     * The barId property.
     */
    @Generated
    private String barId;

    /**
     * Creates an instance of Bar class.
     */
    @Generated
    private Bar() {
    }

    /**
     * Get the barId property: The barId property.
     * 
     * @return the barId value.
     */
    @Generated
    public String getBarId() {
        return this.barId;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of Bar from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of Bar if the JsonReader was pointing to an instance of it, or null if it was pointing to
     * JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the Bar.
     */
    @Generated
    public static Bar fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String barId = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("barId".equals(fieldName)) {
                    barId = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            Bar deserializedBar = new Bar();
            deserializedBar.barId = barId;

            return deserializedBar;
        });
    }
}
