// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

module com.azure.operations.crud {
    requires transitive com.azure.core;
    exports com.azure.operations.crud;
    exports com.azure.operations.crud.models;
    opens com.azure.operations.crud.models to com.azure.core;
}