// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.auth.all;

public final class ReadmeSamples {
    public void readmeSamples() {
        // BEGIN: com.azure.auth.all.readme
        // END: com.azure.auth.all.readme
    }
}
