// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.client.multi.implementation;

import com.azure.client.multi.MultipleClientsServiceVersion;
import com.azure.core.http.HttpPipeline;
import com.azure.core.http.HttpPipelineBuilder;
import com.azure.core.http.policy.RetryPolicy;
import com.azure.core.http.policy.UserAgentPolicy;
import com.azure.core.util.serializer.JacksonAdapter;
import com.azure.core.util.serializer.SerializerAdapter;

/**
 * Initializes a new instance of the MultipleClientsClient type.
 */
public final class MultipleClientsClientImpl {
    /**
     * Supported endpoints (protocol and hostname, for example:
     * https://westus.client.auth.com).
     */
    private final String endpoint;

    /**
     * Gets Supported endpoints (protocol and hostname, for example:
     * https://westus.client.auth.com).
     * 
     * @return the endpoint value.
     */
    public String getEndpoint() {
        return this.endpoint;
    }

    /**
     * Service version.
     */
    private final MultipleClientsServiceVersion serviceVersion;

    /**
     * Gets Service version.
     * 
     * @return the serviceVersion value.
     */
    public MultipleClientsServiceVersion getServiceVersion() {
        return this.serviceVersion;
    }

    /**
     * The HTTP pipeline to send requests through.
     */
    private final HttpPipeline httpPipeline;

    /**
     * Gets The HTTP pipeline to send requests through.
     * 
     * @return the httpPipeline value.
     */
    public HttpPipeline getHttpPipeline() {
        return this.httpPipeline;
    }

    /**
     * The serializer to serialize an object into a string.
     */
    private final SerializerAdapter serializerAdapter;

    /**
     * Gets The serializer to serialize an object into a string.
     * 
     * @return the serializerAdapter value.
     */
    public SerializerAdapter getSerializerAdapter() {
        return this.serializerAdapter;
    }

    /**
     * The ClientOnesImpl object to access its operations.
     */
    private final ClientOnesImpl clientOnes;

    /**
     * Gets the ClientOnesImpl object to access its operations.
     * 
     * @return the ClientOnesImpl object.
     */
    public ClientOnesImpl getClientOnes() {
        return this.clientOnes;
    }

    /**
     * The ClientTwoesImpl object to access its operations.
     */
    private final ClientTwoesImpl clientTwoes;

    /**
     * Gets the ClientTwoesImpl object to access its operations.
     * 
     * @return the ClientTwoesImpl object.
     */
    public ClientTwoesImpl getClientTwoes() {
        return this.clientTwoes;
    }

    /**
     * Initializes an instance of MultipleClientsClient client.
     * 
     * @param endpoint Supported endpoints (protocol and hostname, for example:
     * https://westus.client.auth.com).
     * @param serviceVersion Service version.
     */
    public MultipleClientsClientImpl(String endpoint, MultipleClientsServiceVersion serviceVersion) {
        this(new HttpPipelineBuilder().policies(new UserAgentPolicy(), new RetryPolicy()).build(),
            JacksonAdapter.createDefaultSerializerAdapter(), endpoint, serviceVersion);
    }

    /**
     * Initializes an instance of MultipleClientsClient client.
     * 
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param endpoint Supported endpoints (protocol and hostname, for example:
     * https://westus.client.auth.com).
     * @param serviceVersion Service version.
     */
    public MultipleClientsClientImpl(HttpPipeline httpPipeline, String endpoint,
        MultipleClientsServiceVersion serviceVersion) {
        this(httpPipeline, JacksonAdapter.createDefaultSerializerAdapter(), endpoint, serviceVersion);
    }

    /**
     * Initializes an instance of MultipleClientsClient client.
     * 
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param serializerAdapter The serializer to serialize an object into a string.
     * @param endpoint Supported endpoints (protocol and hostname, for example:
     * https://westus.client.auth.com).
     * @param serviceVersion Service version.
     */
    public MultipleClientsClientImpl(HttpPipeline httpPipeline, SerializerAdapter serializerAdapter, String endpoint,
        MultipleClientsServiceVersion serviceVersion) {
        this.httpPipeline = httpPipeline;
        this.serializerAdapter = serializerAdapter;
        this.endpoint = endpoint;
        this.serviceVersion = serviceVersion;
        this.clientOnes = new ClientOnesImpl(this);
        this.clientTwoes = new ClientTwoesImpl(this);
    }
}
