// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.client.customization;

import com.azure.client.customization.implementation.CustomizationSamplesImpl;
import com.azure.client.customization.implementation.models.GetBarRequest;
import com.azure.client.customization.implementation.models.GetFooRequest;
import com.azure.client.customization.models.BarModel;
import com.azure.client.customization.models.Foo;
import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.http.rest.Response;
import com.azure.core.util.BinaryData;

/**
 * Initializes a new instance of the synchronous CustomizationClient type.
 */
@ServiceClient(builder = CustomizationClientBuilder.class)
public final class CustomizationClient {

    @Generated
    private final CustomizationSamplesImpl serviceClient;

    /**
     * Initializes an instance of CustomizationClient class.
     *
     * @param serviceClient the service client implementation.
     */
    @Generated
    CustomizationClient(CustomizationSamplesImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * The getFooDetails operation.
     * <p><strong>Request Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     foo (Required): {
     *         fooId: String (Required)
     *     }
     * }
     * }
     * </pre>
     *
     * @param getFooRequest The getFooRequest parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> getFooDetailsWithResponse(BinaryData getFooRequest, RequestOptions requestOptions) {
        return this.serviceClient.getFooDetailsWithResponse(getFooRequest, requestOptions);
    }

    /**
     * The getBar operation.
     * <p><strong>Request Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     bar (Required): {
     *         barName: String (Required)
     *         baz (Required): {
     *             bazName: String (Required)
     *         }
     *     }
     * }
     * }
     * </pre>
     *
     * @param getBarRequest The getBarRequest parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> getBarWithResponse(BinaryData getBarRequest, RequestOptions requestOptions) {
        return this.serviceClient.getBarWithResponse(getBarRequest, requestOptions);
    }

    /**
     * The getFooDetails operation.
     *
     * @param fooName The fooName parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void getFooDetails(Foo fooName) {
        // Generated convenience method for getFooDetailsWithResponse
        RequestOptions requestOptions = new RequestOptions();
        GetFooRequest getFooRequestObj = new GetFooRequest(fooName);
        BinaryData getFooRequest = BinaryData.fromObject(getFooRequestObj);
        getFooDetailsWithResponse(getFooRequest, requestOptions).getValue();
    }

    /**
     * The getBar operation.
     *
     * @param bar The bar parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void getBar(BarModel bar) {
        // Generated convenience method for getBarWithResponse
        RequestOptions requestOptions = new RequestOptions();
        GetBarRequest getBarRequestObj = new GetBarRequest(bar);
        BinaryData getBarRequest = BinaryData.fromObject(getBarRequestObj);
        getBarWithResponse(getBarRequest, requestOptions).getValue();
    }
}
