// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.client.customization.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The BarModel model.
 */
@Immutable
public final class BarModel implements JsonSerializable<BarModel> {

    /*
     * The barName property.
     */
    @Generated
    private final String barName;

    /**
     * Creates an instance of BarModel class.
     *
     * @param barName the barName value to set.
     * @param bazName the bazName value to set.
     */
    @Generated
    public BarModel(String barName, Baz bazName) {
        this.barName = barName;
        this.bazName = bazName;
    }

    /**
     * Get the barName property: The barName property.
     *
     * @return the barName value.
     */
    @Generated
    public String getBarName() {
        return this.barName;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("barName", this.barName);
        jsonWriter.writeJsonField("baz", this.bazName);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of BarModel from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of BarModel if the JsonReader was pointing to an instance of it, or null if it was pointing
     * to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the BarModel.
     */
    @Generated
    public static BarModel fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String barName = null;
            Baz bazName = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("barName".equals(fieldName)) {
                    barName = reader.getString();
                } else if ("baz".equals(fieldName)) {
                    bazName = Baz.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }
            return new BarModel(barName, bazName);
        });
    }

    /*
     * The baz property.
     */
    @Generated
    private final Baz bazName;

    /**
     * Get the bazName property: The baz property.
     *
     * @return the bazName value.
     */
    @Generated
    public Baz getBazName() {
        return this.bazName;
    }
}
