// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.client.customization.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The Baz model.
 */
@Immutable
public final class Baz implements JsonSerializable<Baz> {

    /*
     * The bazName property.
     */
    @Generated
    private final String bazName;

    /**
     * Creates an instance of Baz class.
     *
     * @param bazName the bazName value to set.
     */
    @Generated
    public Baz(String bazName) {
        this.bazName = bazName;
    }

    /**
     * Get the bazName property: The bazName property.
     *
     * @return the bazName value.
     */
    @Generated
    public String getBazName() {
        return this.bazName;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("bazName", this.bazName);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of Baz from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of Baz if the JsonReader was pointing to an instance of it, or null if it was pointing to
     * JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the Baz.
     */
    @Generated
    public static Baz fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String bazName = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("bazName".equals(fieldName)) {
                    bazName = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            return new Baz(bazName);
        });
    }
}
