// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.operations.crud.implementation;

import com.azure.operations.crud.models.Widget;

/**
 * This is the Helper class to enable json merge patch serialization for a model.
 */
public class JsonMergePatchHelper {
    private static WidgetAccessor widgetAccessor;

    public interface WidgetAccessor {
        Widget prepareModelForJsonMergePatch(Widget widget, boolean jsonMergePatchEnabled);
    }

    public static void setWidgetAccessor(WidgetAccessor accessor) {
        widgetAccessor = accessor;
    }

    public static WidgetAccessor getWidgetAccessor() {
        return widgetAccessor;
    }
}
