// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.client.customization.implementation.models;

import com.azure.client.customization.models.BarModel;
import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The GetBarRequest model.
 */
@Immutable
public final class GetBarRequest implements JsonSerializable<GetBarRequest> {

    /*
     * The bar property.
     */
    @Generated
    private final BarModel bar;

    /**
     * Creates an instance of GetBarRequest class.
     *
     * @param bar the bar value to set.
     */
    @Generated
    public GetBarRequest(BarModel bar) {
        this.bar = bar;
    }

    /**
     * Get the bar property: The bar property.
     *
     * @return the bar value.
     */
    @Generated
    public BarModel getBar() {
        return this.bar;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeJsonField("bar", this.bar);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of GetBarRequest from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of GetBarRequest if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the GetBarRequest.
     */
    @Generated
    public static GetBarRequest fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            BarModel bar = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("bar".equals(fieldName)) {
                    bar = BarModel.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }
            return new GetBarRequest(bar);
        });
    }
}
