// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.client.customization.implementation.models;

import com.azure.client.customization.models.Foo;
import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The GetFooRequest model.
 */
@Immutable
public final class GetFooRequest implements JsonSerializable<GetFooRequest> {

    /*
     * The foo property.
     */
    @Generated
    private final Foo fooName;

    /**
     * Creates an instance of GetFooRequest class.
     *
     * @param fooName the fooName value to set.
     */
    @Generated
    public GetFooRequest(Foo fooName) {
        this.fooName = fooName;
    }

    /**
     * Get the fooName property: The foo property.
     *
     * @return the fooName value.
     */
    @Generated
    public Foo getFooName() {
        return this.fooName;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeJsonField("foo", this.fooName);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of GetFooRequest from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of GetFooRequest if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the GetFooRequest.
     */
    @Generated
    public static GetFooRequest fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            Foo fooName = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("foo".equals(fieldName)) {
                    fooName = Foo.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }
            return new GetFooRequest(fooName);
        });
    }
}
